# Generated by Django 5.0 on 2024-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_backend', '0002_alter_faq_helpful'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
